# markdownlint configuration for OmniFetch-Wiki
# Professional documentation standards following industry best practices

# Default configuration
default: true

# Rule configurations
MD001: true  # Header levels should only increment by one level at a time

MD003:
  # Header style: atx (# Header) for consistency
  style: "atx"

MD004:
  # Unordered list style: consistent dash usage
  style: "dash"

MD005: true  # List indentation consistency

MD007:
  # Unordered list indentation: 2 spaces for readability
  indent: 2
  start_indented: false

MD009:
  # Trailing spaces: allow 2 for line breaks
  br_spaces: 2
  list_item_empty_lines: false
  strict: false

MD010: true  # Hard tabs not allowed - use spaces consistently

MD011: true  # Reversed link syntax prevention

MD012:
  # Multiple consecutive blank lines: max 2 for section separation
  maximum: 2

MD013:
  # Line length: 150 characters for better readability in documentation
  line_length: 150
  # Exclude code blocks and tables from line length checks
  code_blocks: false
  tables: false
  headers: false

MD014: true  # Dollar signs used before commands without showing output

MD018: true  # No space after hash on atx style header

MD019: true  # Multiple spaces after hash on atx style header

MD020: true  # No space inside hashes on closed atx style header

MD021: true  # Multiple spaces inside hashes on closed atx style header

MD022: false  # Headers should be surrounded by blank lines: disabled for flexible documentation formatting

MD023: true  # Headers must start at the beginning of the line

MD024:
  # Multiple headers with the same content allowed in different sections
  allow_different_nesting: true
  siblings_only: false

MD025:
  # Multiple top level headers: allow with front matter title
  front_matter_title: "^\\s*title\\s*[:=]"
  level: 1

MD026: false  # Trailing punctuation in header: disabled for FAQ sections with questions

MD027: true  # Multiple spaces after blockquote symbol

MD028: true  # Blank line inside blockquote

MD029:
  # Ordered list item prefix: sequential numbering
  style: "ordered"

MD030:
  # Spaces after list markers: consistent spacing
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

MD031: true  # Fenced code blocks should be surrounded by blank lines

MD032: true  # Lists should be surrounded by blank lines

MD033:
  # Inline HTML: allow specific elements commonly used in documentation
  allowed_elements: ["br", "sub", "sup", "kbd", "mark", "details", "summary", "abbr", "div", "p", "h1", "h2", "h3", "h4", "h5", "h6", "em", "strong", "img"]

MD034: true  # Bare URL used (should use link syntax)

MD035:
  # Horizontal rule style: consistent three-dash format
  style: "---"

MD036: true  # Emphasis used instead of a header

MD037: true  # Spaces inside emphasis markers

MD038: true  # Spaces inside code span elements

MD039: true  # Spaces inside link text

MD040: true  # Fenced code blocks should have a language specified

MD041: false  # First line in file should be a top level header (disabled for documentation flexibility)

MD042: true  # No empty links

MD043: false  # Required header structure (disabled for flexibility)

MD044:
  # Proper names should have correct capitalization
  names: ["OmniFetch", "CloudKit", "GitHub", "MkDocs", "Sonarr", "Radarr", "Lidarr", "SABnzbd", "Jellyseerr", "iOS", "iPadOS", "tvOS", "API", "HTTP", "HTTPS", "JSON", "YAML", "XML", "SQL", "CSS", "HTML", "URL", "URI", "Docker", "macOS", "iCloud", "App Store", "TestFlight", "Swift", "SwiftUI", "Python", "JavaScript", "TypeScript"]
  code_blocks: false
  html_elements: false

MD045: true  # Images should have alternate text (alt text)

MD046:
  # Code block style: allow both fenced and indented for flexibility
  style: "consistent"

MD047: true  # Files should end with a single newline character

MD048:
  # Code fence style: backticks for consistency
  style: "backtick"

MD049:
  # Emphasis style: asterisk for consistency
  style: "asterisk"

MD050:
  # Strong style: asterisk for consistency
  style: "asterisk"

MD051: true  # Link fragments should be valid

MD052: true  # Reference links and images should use a label that is defined

MD053: true  # Link and image reference definitions should be needed

# Additional modern rules (if supported)
MD054: true  # Link and image style consistency
MD055: true  # Table pipe style consistency
MD056: true  # Table column count consistency