# Site Configuration
site_name: "OmniFetch"
site_url: "https://noodlemctwoodle.github.io/OmniFetch-Wiki/"
site_description: "OmniFetch - An iOS application for monitoring and managing media services including Sonarr, Radarr, Lidarr, Jellyseerr, and SABnzbd with CloudKit sync and real-time notifications."
site_author: "OmniFetch Development Team"

# Repository information
repo_name: "noodlemctwoodle/OmniFetch-Wiki"
repo_url: "https://github.com/noodlemctwoodle/OmniFetch-Wiki"
edit_uri: "edit/main/docs/"

# Copyright
copyright: "Copyright &copy; 2025 OmniFetch. All rights reserved."

# Configuration
theme:
  name: material
  language: en
  logo: assets/images/app/omnifetch-icon.png
  favicon: assets/images/app/omnifetch-icon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # Announcements
    - announce.dismiss
    # Content
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    # Header
    - header.autohide
    # Navigation
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # Search
    - search.highlight
    - search.share
    - search.suggest
    # Table of contents
    - toc.follow
    - toc.integrate
  icon:
    edit: material/pencil
    view: material/eye
    tag:
      default: material/tag
    admonition:
      note: material/pencil-circle
      abstract: material/clipboard-text
      info: material/information
      tip: material/fire
      success: material/check
      question: material/help-circle
      warning: material/alert
      failure: material/close-circle
      danger: material/lightning-bolt
      bug: material/shield-bug
      example: material/test-tube
      quote: material/format-quote-close

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.$|&[lg]t;'
  # - material-plausible  # Disabled - plugin not available
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
      cache_safe: true
  # Note: optimize plugin not available, removed for compatibility
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_themed: true
      auto_caption: true
      caption_position: bottom
      background: rgba(0, 0, 0, 0.9)
      skip_classes:
        - no-lightbox
        - twemoji
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false
  - img2fig
  - section-index
  # Note: social plugin not available, removed for compatibility
  # Social media cards feature would require mkdocs-material[imaging]

# Custom CSS and JavaScript
extra_css:
  # Load CSS files in logical order for proper cascade
  - assets/stylesheets/_base.css          # Variables and root styles first
  - assets/stylesheets/_navigation.css    # Header and navigation
  - assets/stylesheets/_components.css    # Cards, buttons, tables, admonitions
  - assets/stylesheets/_layout.css        # Responsive layout and mobile styles
  - assets/stylesheets/_gallery.css       # Image gallery and lightbox
  - assets/stylesheets/_consent.css       # Cookie consent banner
  - assets/stylesheets/_animations.css    # Keyframe animations and effects
  - assets/stylesheets/custom.css         # Keep existing custom overrides

extra_javascript:
  - assets/javascripts/consent.js
  - assets/javascripts/extra.js
  - assets/javascripts/carousel.js

# Extra configuration
extra:
  generator: false
  version:
    provider: mike
    default: stable
  # Plausible Analytics configuration (disabled - plugin not available)
  # analytics:
  #   provider: plausible
  #   domain: omnifetch.app
  #   src: https://plausible.io/js/script.file-downloads.hash.outbound-links.pageview-props.tagged-events.js
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: 1
        note: >
          Thanks for your feedback! Help us improve by
          <a href="https://github.com/noodlemctwoodle/OmniFetch-Wiki/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">sharing more details</a>.
      - icon: material/emoticon-sad-outline
        name: This page could be improved
        data: 0
        note: >
          Thanks for your feedback! Help us improve by
          <a href="https://github.com/noodlemctwoodle/OmniFetch-Wiki/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">opening an issue</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://noodlemctwoodle.github.io/OmniFetch-Wiki/
      name: OmniFetch on GitHub
    - icon: fontawesome/brands/app-store-ios
      link: https://apps.apple.com/app/omnifetch/id1234567890
      name: Download on App Store
  status:
    new: "New feature documentation"
    deprecated: "This feature is deprecated"
  tags:
    iOS: ios
    Configuration: config
    Webhooks: webhooks
    Services: services
  # Schema.org structured data
  schema:
    type: "WebSite"
    name: "OmniFetch Documentation"
    url: "https://noodlemctwoodle.github.io/OmniFetch-Wiki/"
    description: "Comprehensive documentation for OmniFetch iOS application"
    author:
      type: "Organization"
      name: "OmniFetch Development Team"
    sameAs:
      - "https://github.com/noodlemctwoodle/OmniFetch"
      - "https://apps.apple.com/app/omnifetch"
    potentialAction:
      type: "SearchAction"
      target: "https://noodlemctwoodle.github.io/OmniFetch-Wiki/search/?q={search_term_string}"
      query-input: "required name=search_term_string"
  # Consent system disabled - Plausible Analytics doesn't require consent
  # It's privacy-friendly, cookieless, and GDPR compliant by design

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      title: "On this page"
      permalink_title: "Anchor link to this section"
      toc_depth: 3
      separator: "-"
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: noodlemctwoodle
      repo: OmniFetch-Wiki
      provider: github
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      restrict_base_path: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: chart
          class: chart
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - OmniFetch App:
    - Overview: app/index.md
    - Installation: app/installation.md
    - Configuration: app/configuration.md
    - Features:
      - Webhooks: app/features/webhooks.md
      - Widgets: app/features/widgets.md
      - CloudKit Sync: app/features/cloudkit-sync.md
    - Settings:
      - Initial Setup: app/settings/initial-setup.md
  - Services:
    - Overview: services/index.md
    - Sonarr:
      - Overview: services/sonarr/index.md
      - Setup: services/sonarr/setup.md
      - Webhooks: services/sonarr/webhooks.md
    - Radarr:
      - Overview: services/radarr/index.md
      - Setup: services/radarr/setup.md
      - Webhooks: services/radarr/webhooks.md
    - Lidarr:
      - Overview: services/lidarr/index.md
      - Setup: services/lidarr/setup.md
      - Webhooks: services/lidarr/webhooks.md
    - Jellyseerr:
      - Overview: services/jellyseerr/index.md
      - Setup: services/jellyseerr/setup.md
      - Webhooks: services/jellyseerr/webhooks.md
    - SABnzbd:
      - Overview: services/sabnzbd/index.md
      - Setup: services/sabnzbd/setup.md
      - Webhooks: services/sabnzbd/webhooks.md
      - Script: services/sabnzbd/omnifetch-webhook.py
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQ: troubleshooting/faq.md
  - Release Notes:
    - Latest: release-notes/index.md
    - Build 248: release-notes/v0.0.4-248.md
    - Build 239: release-notes/v0.0.4-239.md
  - Contributing:
    - Translation Guide: contributing/translation-guide.md
  - Analytics & Privacy: analytics.md