site_name: OmniFetch Documentation
site_url: https://noodlemctwoodle.github.io/OmniFetch-Wiki
site_description: Comprehensive documentation for OmniFetch - A SwiftUI application for monitoring and managing media services

# Repository (commented out to hide from header)
# repo_name: noodlemctwoodle/OmniFetch-Wiki
# repo_url: https://github.com/noodlemctwoodle/OmniFetch-Wiki

# Copyright
copyright: Copyright &copy; 2025 OmniFetch

# Configuration
theme:
  name: material
  language: en
  logo: assets/images/Icon-iOS-Default-1024x1024@1x.png
  favicon: assets/images/Icon-iOS-Default-1024x1024@1x.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    edit: material/pencil
    view: material/eye
    tag:
      default: material/tag
    admonition:
      note: material/pencil-circle
      abstract: material/clipboard-text
      info: material/information
      tip: material/fire
      success: material/check
      question: material/help-circle
      warning: material/alert
      failure: material/close-circle
      danger: material/lightning-bolt
      bug: material/shield-bug
      example: material/test-tube
      quote: material/format-quote-close

# Plugins
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css

# Extra configuration
extra:
  generator: false

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: noodlemctwoodle
      repo: OmniFetch-Wiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: setup/installation.md
    - Quick Start: setup/quick-start.md
    - OmniFetch App: setup/omnifetch-app.md
  - Configuration:
    - Overview: setup/configuration.md
    - Service Setup:
      - Sonarr: setup/services/sonarr.md
      - Radarr: setup/services/radarr.md
      - Lidarr: setup/services/lidarr.md
      - Jellyseerr: setup/services/jellyseerr.md
      - SABnzbd: setup/services/sabnzbd.md
  - Services:
    - Overview: services/index.md
    - Sonarr: services/sonarr.md
    - Radarr: services/radarr.md
    - Lidarr: services/lidarr.md
    - Jellyseerr: services/jellyseerr.md
    - SABnzbd: services/sabnzbd.md
  - Features:
    - Notifications: features/notifications.md
    - Webhooks: features/webhooks.md
    - Widgets: features/widgets.md
    - CloudKit Sync: features/cloudkit-sync.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQ: troubleshooting/faq.md